# Input/output configuration
input_dir: data/all_events/raw
output_dir: /Users/lucascurtin/Desktop/QGNN Repos/HepTrkX-quantum/data/piecewise_data
#output_dir: data/example_event/graph-no-cut

n_files: 10

# Graph building configuration
selection:
    pt_min: 1. # GeV
    phi_slope_max: 0.0006
    z0_max: 100
    n_phi_sections: 8
    n_eta_sections: 2
    eta_range: [-5, 5]